### ISSUE TITLE
Attribute reader for @xml_data

### ISSUE THREAD

**Issue by danielpuglisi** [viafintech/camt_parser#61]
Heyo!

I was wondering if we could potentially introduce an attribute reader for `@xml_data`?

Maybe by directly adding `attr_reader :xml_data` to each class or by adding a new superclass `CamtParser::XmlData` from which the other classes could inherit?

**Comment by tobischo** [comment]
The goal would be to have it accessible and be able to access any fields that might not yet be available in camt_parser explicitly?

**Comment by danielpuglisi** [comment]
Yes, exactly.

**Comment by tobischo** [comment]
@danielpuglisi 
I added the changes to latest master. If you could rebase your changes from https://github.com/viafintech/camt_parser/pull/60 or close the MR if you do not deem it necessary anymore, then I would prepare a new release.

**Comment by danielpuglisi** [comment]
Perfect, thank you! I just rebased #60.
